app: dragon-ws
service: dragon-ws
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  apiGateway:
    restApiId: r${env.API_GATEWAY_ID}
    restApiRootResourceId: ${env.API_GATEWAY_ROOT_ID}
  iam:
    role:

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join:
          - ""
          - "arn:aws:s3:::"

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  dragon_ws:
    handler: dist/src/index.handler
    
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    excludeFiles: test/**
