app: dragon-ws
service: dragon-ws
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  dragon_ws:
    handler: dist/src/index.handler
    events:
      - http: 
          path: /dragons
          method: GET
    
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    excludeFiles: test/**
